### ISSUE TITLE
 getVideoMeta not working properly with latest v1.4.20

### ISSUE THREAD

**Issue by seth100** [drawrowfly/tiktok-scraper#505]
Hi,

I have a code that does the extraction of the video metadata:

```js
(async () => {
    try {
        const videoMeta = await TikTokScraper.getVideoMeta('https://www.tiktok.com/@tiktok/video/[ID]', options);
        console.log(videoMeta);
    } catch (error) {
        console.log(error);
    }
})();
```

and it was working fine with **`v1.4.16`**, but now I get:

```
Error: Can't extract video metadata: https://www.tiktok.com/@tiktok/video/[ID]
tiktok-scraper-container   |     at TikTokScraper.getVideoMetadata (/mydata/node_modules/tiktok-scraper/build/core/TikTok.js:797:15)
tiktok-scraper-container   |     at async TikTokScraper.getVideoMeta (/mydata/node_modules/tiktok-scraper/build/core/TikTok.js:808:25)
tiktok-scraper-container   |     at async Object.exports.getVideoMeta (/mydata/node_modules/tiktok-scraper/build/entry.js:169:20)
tiktok-scraper-container   |     at async downloadVideo (/mydata/src/services/downloader.service.js:29:19)
```

only when the Docker container (where I run NodeJS with the `tiktok-scraper`) is running a my remote server.
If I just run my NodeJS server in local or build and run the Docker container in local everything just works fine.

**To Reproduce**
- Used OS: **Ubuntu 20.10**
- NodeJs Version (node -v): **`v14.16.0` inside a Docker container**
- Scraper Version (tiktok-scraper --version): **`v1.4.20`**
- CLI or Module: **module**
- Used method: **`TikTokScraper.getVideoMeta`**
- Used options: **none (default)**
- Do you run the scraper through Proxy, VPN, VPS? **Yes, running on a remote server using Apache2 httpd and behind a NGINX proxy**
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! **Yes, I tried only with public profiles!**
- Preferably provide URL to the profile,hashtag,video and etc page: **I tried many videos, it was used to work with older `v1.4.16`**

Thanks

**Comment by drawrowfly** [comment]
Can't confirm, working fine from mine side

**Comment by drawrowfly** [comment]
You were right, i've started seeing those changes with the delay from mine side. Update is coming

**Comment by drawrowfly** [comment]
Fixed in @1.4.22

**Comment by seth100** [comment]
thanks @drawrowfly, just tried and I'm still having the same issue even with `1.4.22`

**Comment by lau1944** [comment]
me too

**Comment by youngvo** [comment]
@seth100 @lau1944 are you guys using session to download? if yes, let include the session like the follow:
```
let options = {
		sessionList: ['sid_tt=upwdsdldldhaldadsadjk; sessionid=upwdsdldldhaldadsadjk; sessionid_ss=upwdsdldldhaldadsadjk;'],
	};
``` 
You have to include both sid_tt, sessionid and sessionid_ss

**Comment by seth100** [comment]
@youngvo I'm not using session, just the default options
